#pragma once

#ifndef __ENUM_H__
#define __ENUM_H__

enum COMBAT { COMBAT_WIN, COMBAT_LOSE, COMBAT_RUN, COMBAT_END };
enum TYPE { TYPE_SWORD, TYPE_ARMOR, TYPE_END };
enum LEVEL { LEVEL_1, LEVEL_2, LEVEL_3, LEVEL_END };
enum STATE{STATE_EQUIP, STATE_UNEQUIP, STATE_END};


#endif // !__ENUM_H__
